- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

  tasks:
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/cli_tools.yml
