- name: Install fzf
  action: >
    {{ ansible_pkg_mgr }} name=fzf
  become: false
  tags:
    - cli

- name: Install atuin
  shell: /bin/bash -c "$(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)"
  become: false
  tags:
    - cli
