- name: Install zsh
  action: >
    {{ ansible_pkg_mgr }} name=zsh
  become: false
  tags:
    - zsh
- name: Change shell to zsh
  shell: chsh -s `which zsh`
  tags:
    - zsh

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: Install zsh plugin autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  tags:
    - zsh
